{% set name = "svcs" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/svcs-{{ version }}.tar.gz
  sha256: 64dd74d0c4e8fee79a9ac7550a9d824670b228df390ba1911614e29b59b3f2c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.27.0
    - hatch-vcs
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - attrs >=21.3.0

test:
  imports:
    - svcs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A Flexible Service Locator
  license: MIT
  license_file: LICENSE
  home: https://svcs.hynek.me/en/stable/index.html

extra:
  recipe-maintainers:
    - tdsmith
